export const CohertFirstData2023 = [
  {
    id: 1,
    img: "/Buddha-Fellows/rama-reddy.png",
    title: "K V Rama Subba Reddy",
    desc: "Reddy Nibbles <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh </span>",
    link: "https://www.linkedin.com/in/rama-subba-reddy-k-v-a983b31a7",
  },
  {
    id: 2,
    img: "/Buddha-Fellows/shikha-shashi.png",
    title: "Shikha Shashi",
    desc: "Kikaboni Living <br/> <span class = 'font-lato-regular text-gray-600'> Bihar & Haryana </span>",
    link: "https://www.linkedin.com/in/shashi-shikha-638a4518/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 3,
    img: "/Buddha-Fellows/sarojini.png",
    title: "Sarojini Phadtare",
    desc: "Gud2eat <br/> <span class = 'font-lato-regular text-gray-600'> Maharashtra </span>",
    link: "https://www.linkedin.com/in/sarojini-phadtare-8a3040277",
  },
  {
    id: 4,
    img: "/Buddha-Fellows/kusum-tiwari.png",
    title: "Kusum Tiwari",
    desc: "Mura Collective <br/> <span class = 'font-lato-regular text-gray-600'> New Delhi, Uttarakhand </span>",
    link: "https://www.linkedin.com/in/kusum-tiwari-8b658020/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 5,
    img: "/Buddha-Fellows/rishabh-suri.png",
    title: "Rishabh Suri",
    desc: "Qudrat <br/> <span class = 'font-lato-regular text-gray-600'> Kerala</span> ",

    link: "https://www.linkedin.com/in/rishabh-suri-824b6b161/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 6,
    img: "/Buddha-Fellows/sudhanshu-gupta.png",
    title: "Sudhanshu Gupta",
    desc: "SNL Innovations <br/> <span class = 'font-lato-regular text-gray-600'> Rajasthan, J&K, MP, UP, Maharashtra </span>",
    link: "https://www.linkedin.com/in/sudhgupta/?originalSubdomain=in",
  },
  {
    id: 7,
    img: "/Buddha-Fellows/kamlesh.png",
    title: "Kamlesh M",
    desc: "The Farming Buddha <br/> <span class = 'font-lato-regular text-gray-600'> Karnataka </span>",
    link: "https://www.linkedin.com/in/kamalesh-m-thefarmingbuddha/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 8,
    img: "/Buddha-Fellows/sharad-kumar.png",
    title: "Sharad Kumar Nirala",
    desc: "Indijan Activated Agrifood Pvt. Ltd. <br/> <span class = 'font-lato-regular text-gray-600'> Bihar </span>",
    link: "https://www.linkedin.com/in/sharad-kumar-nirala-4822b9134/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 9,
    img: "/Buddha-Fellows/jaspal-singh.png",
    title: "Jaspal Singh",
    desc: "Gramya <br/> <span class = 'font-lato-regular text-gray-600'> Maharashtra, MP,  NCR, Punjab, Rajasthan </span>",
    link: "https://www.linkedin.com/in/jaspal-singh-157192158/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 10,
    img: "/Buddha-Fellows/sharwan-kumar.png",
    title: "Sharwan Kumar",
    desc: "BK Farm Mechanization <br/> <span class = 'font-lato-regular text-gray-600'> Rajasthan </span>",
    link: "",
  },
  {
    id: 11,
    img: "/Buddha-Fellows/rajesh.png",
    title: "Rajesh Tarate",
    desc: "My Farmer <br/> <span class = 'font-lato-regular text-gray-600'> Maharashtra </span>",
    link: "https://www.linkedin.com/in/rajesh-tarate-3430bb14/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 12,
    img: "/Buddha-Fellows/sathish.png",
    title: "Sathishkumar CAV",
    desc: "Swachha Kaadyam <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh </span>",
    link: "https://www.linkedin.com/in/sathishkumarcav/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 13,
    img: "/Buddha-Fellows/rajul.png",
    title: "Rajul Patkar",
    desc: "Soilsens <br/> <span class = 'font-lato-regular text-gray-600'> Pan India, Global </span>",
    link: "https://www.linkedin.com/in/rajulpatkar/",
  },
  {
    id: 14,
    img: "/Buddha-Fellows/akshay-dixit.png",
    title: "Akshay Dixit",
    desc: "Vesatogo Innovations <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh </span>",
    link: "https://www.linkedin.com/in/akshaydixit2010/",
  },
  {
    id: 15,
    img: "/Buddha-Fellows/manju.png",
    title: "Manju Vasudevan",
    desc: "Forest Post <br/> <span class = 'font-lato-regular text-gray-600'> Kerala </span>",
    link: "https://www.linkedin.com/in/manju-vasudevan-a13846234/",
  },
  {
    id: 16,
    img: "/Buddha-Fellows/sheikh.png",
    title: "Sheikh Ziaur",
    desc: "Paving & Climate <br/> <span class = 'font-lato-regular text-gray-600'> West Bengal </span>",
    link: "https://www.linkedin.com/in/sheikh-ziaur-rahaman/",
  },
  {
    id: 17,
    img: "/Buddha-Fellows/sai-sudha.png",
    title: "Sai Sudha Chebrolu",
    desc: "Bilvam Jaganmaata <br/> Herbals, Livelihood <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh, Gujarat, Odisha, Kerala </span>",
    link: "https://www.linkedin.com/in/sai-sudha-2a959951/?originalSubdomain=in",
  },
  {
    id: 18,
    img: "/Buddha-Fellows/immaculate.png",
    title: "Immaculate Anthony",
    desc: "Arockiasamy IMA <br/> Recreation Livelihoods <br/> <span class = 'font-lato-regular text-gray-600'> Tamil Nadu </span>",
    link: "https://www.linkedin.com/in/immaculate-antony-4560489/?originalSubdomain=in",
  },
  {
    id: 19,
    img: "/Buddha-Fellows/abhijit-sathe.png",
    title: "Abhijit Sathe",
    desc: "JalSevak Solution Climate <br/> <span class = 'font-lato-regular text-gray-600'> Maharashtra, Karnataka, UP, NCR </span>",
    link: "https://www.linkedin.com/in/abhijitsathe/",
  },
  {
    id: 20,
    img: "/Buddha-Fellows/sreerag.png",
    title: "Sreerag Ar",
    desc: "FabUs Livelihoods <br/> <span class = 'font-lato-regular text-gray-600'> Kerala </span>",
    link: "https://www.linkedin.com/in/sreerag-ar/",
  },
  {
    id: 21,
    img: "/Buddha-Fellows/pranjal.png",
    title: "Pranjal Modi",
    desc: "TitLi Livelihoods <br/> <span class = 'font-lato-regular text-gray-600'> Jharkhand, Maharashtra </span>",
    link: "https://www.linkedin.com/in/pranjalmodi/?originalSubdomain=in",
  },
  {
    id: 22,
    img: "/Buddha-Fellows/annu.png",
    title: "Annu Sunny",
    desc: "Graamya <br/> <span class = 'font-lato-regular text-gray-600'> Kerala </span>",
    link: "https://www.linkedin.com/in/annu-sunny-09aa02104/?originalSubdomain=in",
  },
  {
    id: 23,
    img: "/Buddha-Fellows/deepak-kumar.png",
    title: "Deepak Kumar",
    desc: "Yogita Biofarming <br/> <span class = 'font-lato-regular text-gray-600'> West Bengal </span>",
    link: "https://www.linkedin.com/in/deepak-kumar-453a0a76/",
  },
  {
    id: 24,
    img: "/Buddha-Fellows/ashok-gorre.png",
    title: "Ashok Gorre",
    desc: "Rural Rise Agrinery <br/> <span class = 'font-lato-regular text-gray-600'>  Andhra Pradesh </span>",
    link: "https://www.linkedin.com/in/gorre-ashok-48a2891ba/",
  },
  {
    id: 25,
    img: "/Buddha-Fellows/devika.png",
    title: "Devika Chandrashekaran",
    desc: "Fuselage Innovations <br/> <span class = 'font-lato-regular text-gray-600'> Karnataka, Kerala, Tamil Nadu </span>",
    link: "https://www.linkedin.com/in/devika-chandrasekharan/?originalSubdomain=in",
  },
  {
    id: 26,
    img: "/Buddha-Fellows/manash.png",
    title: "Manash Pratim Kalita",
    desc: "Traditional Northeast <br/> <span class = 'font-lato-regular text-gray-600'> Assam </span>",
    link: "https://www.linkedin.com/in/manash-pratim-kalita-89b481101?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 27,
    img: "/Buddha-Fellows/JSRB.png",
    title: "JSRB Kalyani",
    desc: "Earth 360 <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh </span>",
    link: "",
  },
  {
    id: 28,
    img: "/Buddha-Fellows/dhruv-joshi.png",
    title: "Dhruv Joshi",
    desc: "GramSe  <br/> <span class = 'font-lato-regular text-gray-600'> Uttarakhand, NCR </span>",
    link: "https://www.linkedin.com/in/dhruv-joshi-638b5a31/",
  },
];

export const CohertSecondData2022 = [
  {
    id: 1,
    img: "/Buddha-Fellows/namrata.png",
    title: "Namrata Acharya",
    desc: "Khedut Samridhhi Pvt. Ltd.  <br/> <span class = 'font-lato-regular text-gray-600'>  Gujarat </span>",
    link: "https://www.linkedin.com/in/namrata-acharya-0ba4b217a/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 2,
    img: "/Buddha-Fellows/priyjeet.png",
    title: "Priyjeet Bose",
    desc: "BPN Agro and Livestock Pvt. Ltd.  <br/> <span class = 'font-lato-regular text-gray-600'> Chattisgarh </span>",
    link: "https://www.linkedin.com/in/priyjeet-bose-0ab186a8/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 3,
    img: "/Buddha-Fellows/ronald.png",
    title: "Ronald Castelino",
    desc: "Agrinet Food And Beverages Pvt.  Ltd. <br/> <span class = 'font-lato-regular text-gray-600'> Uttarakhand </span>",
    link: "https://www.linkedin.com/in/ronald-castelino-a781b63/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 4,
    img: "/Buddha-Fellows/kalyani.png",
    title: "Kalyani Chavali",
    desc: "Sahrudaya Food Technologies <br/> <span class = 'font-lato-regular text-gray-600'> Maharashtra </span>",
    link: "https://www.linkedin.com/in/kalyani-chavali-65b431133/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 5,
    img: "/Buddha-Fellows/amit.png",
    title: "Amit Godse",
    desc: "Bee Basket Enterprises Pvt. Ltd. <br/> <span class = 'font-lato-regular text-gray-600'>  Maharashtra </span>",
    link: "https://www.linkedin.com/in/amitgodse/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 6,
    img: "/Buddha-Fellows/satyendra.png",
    title: "Satendra Singh Lilhare",
    desc: "Bastar Se Bazar Tak Pvt. Ltd.  <br/> <span class = 'font-lato-regular text-gray-600'>  Chattisgarh </span>",
    link: "https://www.linkedin.com/in/satendrasingh-lilhare-8995b4a6/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 7,
    img: "/Buddha-Fellows/mahesh.png",
    title: "Mahesh Londhe",
    desc: "Agrozee Organics  <br/> <span class = 'font-lato-regular text-gray-600'>  Maharashtra </span>",
    link: "https://www.linkedin.com/in/mahesh-londhe-95869810a/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 8,
    img: "/Buddha-Fellows/prajwal.png",
    title: "Prajwal M",
    desc: "Oscillo Machines Pvt. Ltd.  <br/> <span class = 'font-lato-regular text-gray-600'>  Karnataka </span>",
    link: "https://www.linkedin.com/in/prajwal-m-02517a88/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 9,
    img: "/Buddha-Fellows/rajesh-oza.png",
    title: "Rajesh Oza",
    desc: "Jovaki Agrofood    India <br/> <span class = 'font-lato-regular text-gray-600'>  Rajasthan </span>",
    link: "https://www.linkedin.com/in/rajesh-oza-jovaki/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 10,
    img: "/Buddha-Fellows/mayur.png",
    title: "Mayur Pawar",
    desc: "Wingrow Agritech Producer <br/> Company Ltd. <br/> <span class = 'font-lato-regular text-gray-600'>  Maharashtra </span>",
    link: "https://www.linkedin.com/in/mayur-pawar-290b77161/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 11,
    img: "/Buddha-Fellows/ravi.png",
    title: "Ravi Raj",
    desc: "Koraj Handmade Paper  <br/> <span class = 'font-lato-regular text-gray-600'> Gujarat </span>",
    link: "https://www.linkedin.com/in/ravirajcrafts/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 12,
    img: "/Buddha-Fellows/suhas.png",
    title: "Suhas Ramegowda",
    desc: "Macramedecor Craft Pvt. Ltd. <br/> <span class = 'font-lato-regular text-gray-600'>  Tamil Nadu </span>",
    link: "https://www.linkedin.com/in/suhas-ramegowda/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 13,
    img: "/Buddha-Fellows/satpute.png",
    title: "Rahul Satpute",
    desc: "Bhumitra Laboratories And Soilcare <br/> <span class = 'font-lato-regular text-gray-600'>  Maharashtra </span>",
    link: "https://www.linkedin.com/in/rahul-satpute-b3147911b/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 14,
    img: "/Buddha-Fellows/srinivas-rao.png",
    title: "B Srinivas Rao",
    desc: "Manyam Grains   <br/> <span class = 'font-lato-regular text-gray-600'> Andhra Pradesh </span>",
    link: "",
  },
  {
    id: 15,
    img: "/Buddha-Fellows/angraj.png",
    title: "Angraj Swami",
    desc: "ECOWRAP <br/> <span class = 'font-lato-regular text-gray-600'>  Rajasthan </span>",
    link: "https://www.linkedin.com/in/angrajswami/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
];

export const CohertThirdData2018 = [
  {
    id: 1,
    img: "/Buddha-Fellows/jitendra.png",
    title: "JITENDRA YADAV",
    desc: "IIM LUCKNOW (2018-2020)",
    link: "https://www.linkedin.com/in/jitendra-yadav-76975625/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 2,
    img: "/Buddha-Fellows/ishan.png",
    title: "ISHAN PASRIJA",
    desc: "IIT DELHI (2018-2020)",
    link: "https://www.linkedin.com/in/ishan-pasrija/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 3,
    img: "/Buddha-Fellows/nidhi.png",
    title: "NIDHI PARMAR",
    desc: "IIM UDAIPUR (2018-2020)",
    link: "https://www.linkedin.com/in/nidhi-parmar-5496a413a/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 4,
    img: "/Buddha-Fellows/sumit-jaiswal.png",
    title: "SUMIT JAISWAL",
    desc: "IIM KASHIPUR (2018-2020)",
    link: "https://www.linkedin.com/in/sumit-jaiswal-a6859677/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 5,
    img: "/Buddha-Fellows/darshan.png",
    title: "DARSHAN DORESWAMY",
    desc: "IIM KASHIPUR 2018-2020",
    link: "https://www.linkedin.com/in/darshan-doreswamy-a93569198/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 6,
    img: "/Buddha-Fellows/rakesh-gupta.png",
    title: "RAKESH GUPTA",
    desc: "XISS RANCHI 2018-2020",
    link: "",
  },
  {
    id: 7,
    img: "/Buddha-Fellows/ravi-gajraj.png",
    title: "RAVI GAJRAJ",
    desc: "IIT KANPUR (2018-2020)",
    link: "https://www.linkedin.com/in/ravi-gajraj-110941128/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 8,
    img: "/Buddha-Fellows/kaushlendra-yadav.png",
    title: "KAUSHALENDRA YADAV",
    desc: "IIM AHMEDABAD (2017-2019)",
    link: "https://www.linkedin.com/in/kaushalendra/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 9,
    img: "/Buddha-Fellows/sakuntala.png",
    title: "SAKUNTALA MAJHI",
    desc: "IIM SHILLONG (2017-2019)",
    link: "",
  },
  {
    id: 10,
    img: "/Buddha-Fellows/kolli.png",
    title: "KOLLI MADHU",
    desc: "IIM UDAIPUR (2017-2019)",
    link: "https://www.linkedin.com/in/kolli-madhu-098553126/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 11,
    img: "/Buddha-Fellows/pratyusha.png",
    title: "Y PRATYUSHA",
    desc: "IIM UDAIPUR (2018-2020)",
    link: "",
  },
];

export const SustainedData = [
  {
    id: 1,
    img: "/Buddha-Fellows/kikaboni-updated.jpg",
    title: "Kikaboni Livings",
    location: "Bihar & Haryana",
    link: "https://kikaboni.in/",
    author: "by Shashi Shikha",
  },
  {
    id: 2,
    img: "/Buddha-Fellows/gud2eat-updated.jpg",
    title: "Gud2eat",
    location: "Maharashtra",
    link: "https://www.gud2eat.in/?srsltid=AfmBOop1Ub5TzcrYzDe3EfOBq72bDA1f9xpS05LXzRaZFGtYewaQi0TB",
    author: "by Sarojini Phadtare",
  },
  {
    id: 3,
    img: "/Buddha-Fellows/mura-updated.jpg",
    title: "Mura Collective",
    location: "New Delhi, Uttarakhand",
    link: "https://muracollective.com/",
    author: "by Kusum Tiwari",
  },
  {
    id: 4,
    img: "/Buddha-Fellows/qudrat-updated.jpg",
    title: "Qudrat",
    location: "Kerala",
    link: "https://qudrat.co.in/",
    author: "by Rishabh Suri",
  },
  {
    id: 5,
    img: "/Buddha-Fellows/innovation-updated.jpg",
    title: "SNL Innovations",
    location: "Rajasthan, J&K, MP,UP, Maharashtra",
    link: "https://www.innofarms.co.in/home",
    author: "by Sudhanshu Gupta",
  },
  {
    id: 6,
    img: "/Buddha-Fellows/farming-buddha-updated.jpg",
    title: "The Farming Buddha",
    location: "Karnataka",
    link: "https://www.farmingbuddha.in/",
    author: "by Kamlesh M",
  },
  {
    id: 7,
    img: "/Buddha-Fellows/gramya-updated.jpg",
    title: "Gramya",
    location: "Maharashtra, MP, NCR, Punjab, Rajasthan",
    link: "https://gramya.store/",
    author: "by Jaspal Singh",
  },
];
